//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 04:00:13 PM EST 
//


package city.baltimore.eip.model.motorola.csr;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import city.baltimore.eip.model.CsrElement;


/**
 * <p>Java class for locationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="locationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Location_id" minOccurs="0"/>
 *         &lt;element ref="{}Display_address" minOccurs="0"/>
 *         &lt;element ref="{}Related_table_code" minOccurs="0"/>
 *         &lt;element ref="{}Related_record_id" minOccurs="0"/>
 *         &lt;element ref="{}Address_type_code" minOccurs="0"/>
 *         &lt;element ref="{}Country_code" minOccurs="0"/>
 *         &lt;element ref="{}Street_number" minOccurs="0"/>
 *         &lt;element ref="{}Prefix_direction_code" minOccurs="0"/>
 *         &lt;element ref="{}Prefix_type_code" minOccurs="0"/>
 *         &lt;element ref="{}Street_name" minOccurs="0"/>
 *         &lt;element ref="{}Street_type_code" minOccurs="0"/>
 *         &lt;element ref="{}Suffix_direction_code" minOccurs="0"/>
 *         &lt;element ref="{}City" minOccurs="0"/>
 *         &lt;element ref="{}District" minOccurs="0"/>
 *         &lt;element ref="{}Region" minOccurs="0"/>
 *         &lt;element ref="{}City_zone" minOccurs="0"/>
 *         &lt;element ref="{}Location_details" minOccurs="0"/>
 *         &lt;element ref="{}Building_name" minOccurs="0"/>
 *         &lt;element ref="{}Unit_number" minOccurs="0"/>
 *         &lt;element ref="{}Floor" minOccurs="0"/>
 *         &lt;element ref="{}X_value" minOccurs="0"/>
 *         &lt;element ref="{}Y_value" minOccurs="0"/>
 *         &lt;element ref="{}Created_by" minOccurs="0"/>
 *         &lt;element ref="{}Created_date" minOccurs="0"/>
 *         &lt;element ref="{}Updated_by" minOccurs="0"/>
 *         &lt;element ref="{}Updated_date" minOccurs="0"/>
 *         &lt;element ref="{}Record_version" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "locationType", propOrder = {
    "locationId",
    "displayAddress",
    "relatedTableCode",
    "relatedRecordId",
    "addressTypeCode",
    "countryCode",
    "streetNumber",
    "prefixDirectionCode",
    "prefixTypeCode",
    "streetName",
    "streetTypeCode",
    "suffixDirectionCode",
    "city",
    "district",
    "region",
    "cityZone",
    "locationDetails",
    "buildingName",
    "unitNumber",
    "floor",
    "xValue",
    "yValue",
    "createdBy",
    "createdDate",
    "updatedBy",
    "updatedDate",
    "recordVersion"
})

/**
 * A Geolocation. Added the interface implementation after auto-generation using JAXB. This was for compatibility in generic methods of the CsrToSrMappingServiceImpl.
 * @author james.somerville
 *
 */
public class LocationType implements CsrElement {

    @XmlElement(name = "Location_id")
    protected BigInteger locationId;
    @XmlElement(name = "Display_address")
    protected String displayAddress;
    @XmlElement(name = "Related_table_code")
    protected String relatedTableCode;
    @XmlElement(name = "Related_record_id")
    protected BigInteger relatedRecordId;
    @XmlElement(name = "Address_type_code")
    protected String addressTypeCode;
    @XmlElement(name = "Country_code")
    protected String countryCode;
    @XmlElement(name = "Street_number")
    protected String streetNumber;
    @XmlElement(name = "Prefix_direction_code")
    protected String prefixDirectionCode;
    @XmlElement(name = "Prefix_type_code")
    protected String prefixTypeCode;
    @XmlElement(name = "Street_name")
    protected String streetName;
    @XmlElement(name = "Street_type_code")
    protected String streetTypeCode;
    @XmlElement(name = "Suffix_direction_code")
    protected String suffixDirectionCode;
    @XmlElement(name = "City")
    protected String city;
    @XmlElement(name = "District")
    protected String district;
    @XmlElement(name = "Region")
    protected String region;
    @XmlElement(name = "City_zone")
    protected String cityZone;
    @XmlElement(name = "Location_details")
    protected String locationDetails;
    @XmlElement(name = "Building_name")
    protected String buildingName;
    @XmlElement(name = "Unit_number")
    protected String unitNumber;
    @XmlElement(name = "Floor")
    protected String floor;
    @XmlElement(name = "X_value")
    protected BigDecimal xValue;
    @XmlElement(name = "Y_value")
    protected BigDecimal yValue;
    @XmlElement(name = "Created_by")
    protected BigInteger createdBy;
    @XmlElement(name = "Created_date")
    protected String createdDate;
    @XmlElement(name = "Updated_by")
    protected BigInteger updatedBy;
    @XmlElement(name = "Updated_date")
    protected String updatedDate;
    @XmlElement(name = "Record_version")
    protected BigInteger recordVersion;

    /**
     * Gets the value of the locationId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocationId() {
        return locationId;
    }

    /**
     * Sets the value of the locationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocationId(BigInteger value) {
        this.locationId = value;
    }

    /**
     * Gets the value of the displayAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayAddress() {
        return displayAddress;
    }

    /**
     * Sets the value of the displayAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayAddress(String value) {
        this.displayAddress = value;
    }

    /**
     * Gets the value of the relatedTableCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedTableCode() {
        return relatedTableCode;
    }

    /**
     * Sets the value of the relatedTableCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedTableCode(String value) {
        this.relatedTableCode = value;
    }

    /**
     * Gets the value of the relatedRecordId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRelatedRecordId() {
        return relatedRecordId;
    }

    /**
     * Sets the value of the relatedRecordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRelatedRecordId(BigInteger value) {
        this.relatedRecordId = value;
    }

    /**
     * Gets the value of the addressTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressTypeCode() {
        return addressTypeCode;
    }

    /**
     * Sets the value of the addressTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressTypeCode(String value) {
        this.addressTypeCode = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the streetNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetNumber() {
        return streetNumber;
    }

    /**
     * Sets the value of the streetNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetNumber(String value) {
        this.streetNumber = value;
    }

    /**
     * Gets the value of the prefixDirectionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefixDirectionCode() {
        return prefixDirectionCode;
    }

    /**
     * Sets the value of the prefixDirectionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefixDirectionCode(String value) {
        this.prefixDirectionCode = value;
    }

    /**
     * Gets the value of the prefixTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefixTypeCode() {
        return prefixTypeCode;
    }

    /**
     * Sets the value of the prefixTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefixTypeCode(String value) {
        this.prefixTypeCode = value;
    }

    /**
     * Gets the value of the streetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * Sets the value of the streetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetName(String value) {
        this.streetName = value;
    }

    /**
     * Gets the value of the streetTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetTypeCode() {
        return streetTypeCode;
    }

    /**
     * Sets the value of the streetTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetTypeCode(String value) {
        this.streetTypeCode = value;
    }

    /**
     * Gets the value of the suffixDirectionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffixDirectionCode() {
        return suffixDirectionCode;
    }

    /**
     * Sets the value of the suffixDirectionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffixDirectionCode(String value) {
        this.suffixDirectionCode = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the district property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrict() {
        return district;
    }

    /**
     * Sets the value of the district property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrict(String value) {
        this.district = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the cityZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityZone() {
        return cityZone;
    }

    /**
     * Sets the value of the cityZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityZone(String value) {
        this.cityZone = value;
    }

    /**
     * Gets the value of the locationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationDetails() {
        return locationDetails;
    }

    /**
     * Sets the value of the locationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationDetails(String value) {
        this.locationDetails = value;
    }

    /**
     * Gets the value of the buildingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * Sets the value of the buildingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingName(String value) {
        this.buildingName = value;
    }

    /**
     * Gets the value of the unitNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitNumber() {
        return unitNumber;
    }

    /**
     * Sets the value of the unitNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitNumber(String value) {
        this.unitNumber = value;
    }

    /**
     * Gets the value of the floor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFloor() {
        return floor;
    }

    /**
     * Sets the value of the floor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFloor(String value) {
        this.floor = value;
    }

    /**
     * Gets the value of the xValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getXValue() {
        return xValue;
    }

    /**
     * Sets the value of the xValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setXValue(BigDecimal value) {
        this.xValue = value;
    }

    /**
     * Gets the value of the yValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getYValue() {
        return yValue;
    }

    /**
     * Sets the value of the yValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setYValue(BigDecimal value) {
        this.yValue = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCreatedBy(BigInteger value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDate(String value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUpdatedBy(BigInteger value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the updatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @SuppressWarnings("unchecked")
    public String getUpdatedDate() {
        return updatedDate;
    }

    /**
     * Sets the value of the updatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedDate(String value) {
        this.updatedDate = value;
    }

    /**
     * Gets the value of the recordVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecordVersion() {
        return recordVersion;
    }

    /**
     * Sets the value of the recordVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecordVersion(BigInteger value) {
        this.recordVersion = value;
    }

}
