//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 04:00:13 PM EST 
//


package city.baltimore.eip.model.motorola.csr;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the city.baltimore.eip.model.motorola.csr package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CountryCode_QNAME = new QName("", "Country_code");
    private final static QName _DisplayName_QNAME = new QName("", "Display_name");
    private final static QName _CustomAttributeDefsDesc_QNAME = new QName("", "Custom_attribute_defs_desc");
    private final static QName _SearchDisplayName_QNAME = new QName("", "Search_display_name");
    private final static QName _GeoLocation_QNAME = new QName("", "Geo_location");
    private final static QName _ArrivalTime_QNAME = new QName("", "Arrival_time");
    private final static QName _ParentPrcInstanceId_QNAME = new QName("", "Parent_prc_instance_id");
    private final static QName _PhoneDescription_QNAME = new QName("", "Phone_description");
    private final static QName _PhoneNumber_QNAME = new QName("", "Phone_number");
    private final static QName _ElectronicAddress_QNAME = new QName("", "Electronic_address");
    private final static QName _MethodReceivedCode_QNAME = new QName("", "Method_received_code");
    private final static QName _LocationDetails_QNAME = new QName("", "Location_details");
    private final static QName _PrcDescription_QNAME = new QName("", "Prc_description");
    private final static QName _StatusDescription_QNAME = new QName("", "Status_description");
    private final static QName _AttributeDatatypeCode_QNAME = new QName("", "Attribute_datatype_code");
    private final static QName _AttributeCodes_QNAME = new QName("", "Attribute_codes");
    private final static QName _LinkedReasonDescription_QNAME = new QName("", "Linked_reason_description");
    private final static QName _UnitNumber_QNAME = new QName("", "Unit_number");
    private final static QName _ConfigLocationValue_QNAME = new QName("", "Config_location_value");
    private final static QName _XValue_QNAME = new QName("", "X_value");
    private final static QName _TypeCustomAttributeId_QNAME = new QName("", "Type_custom_attribute_id");
    private final static QName _ResElectronicAddresses_QNAME = new QName("", "Res_electronic_addresses");
    private final static QName _PhoneCode_QNAME = new QName("", "Phone_code");
    private final static QName _ElectronicAddressDescription_QNAME = new QName("", "Electronic_address_description");
    private final static QName _PrcParticipants_QNAME = new QName("", "Prc_participants");
    private final static QName _ParentActivityId_QNAME = new QName("", "Parent_activity_id");
    private final static QName _Details_QNAME = new QName("", "Details");
    private final static QName _PriorityCode_QNAME = new QName("", "Priority_code");
    private final static QName _CompletedDate_QNAME = new QName("", "Completed_date");
    private final static QName _Id_QNAME = new QName("", "Id");
    private final static QName _PrcActivities_QNAME = new QName("", "Prc_activities");
    private final static QName _StopDate_QNAME = new QName("", "Stop_date");
    private final static QName _RelatedRecordId_QNAME = new QName("", "Related_record_id");
    private final static QName _UpdatedDate_QNAME = new QName("", "Updated_date");
    private final static QName _ElectronicAddressCode_QNAME = new QName("", "Electronic_address_code");
    private final static QName _ResPhone_QNAME = new QName("", "Res_phone");
    private final static QName _LinkedPrcCode_QNAME = new QName("", "Linked_prc_code");
    private final static QName _ResName_QNAME = new QName("", "Res_name");
    private final static QName _SuffixDirectionCode_QNAME = new QName("", "Suffix_direction_code");
    private final static QName _ParticipantCode_QNAME = new QName("", "Participant_code");
    private final static QName _ResPhones_QNAME = new QName("", "Res_phones");
    private final static QName _UpdatedBy_QNAME = new QName("", "Updated_by");
    private final static QName _PrcHistoricalGeoAreas_QNAME = new QName("", "Prc_historical_geo_areas");
    private final static QName _ResNames_QNAME = new QName("", "Res_names");
    private final static QName _ResAttribute_QNAME = new QName("", "Res_attribute");
    private final static QName _IsSourceOfPrcInd_QNAME = new QName("", "Is_source_of_prc_ind");
    private final static QName _OutcomeCode_QNAME = new QName("", "Outcome_code");
    private final static QName _CreatedBy_QNAME = new QName("", "Created_by");
    private final static QName _UnlinkedReasonCode_QNAME = new QName("", "Unlinked_reason_code");
    private final static QName _NameTypeItemDescription_QNAME = new QName("", "Name_type_item_description");
    private final static QName _PrcLinkedProcesses_QNAME = new QName("", "Prc_linked_processes");
    private final static QName _RelatedTableCode_QNAME = new QName("", "Related_table_code");
    private final static QName _UnlinkedDate_QNAME = new QName("", "Unlinked_date");
    private final static QName _CityZone_QNAME = new QName("", "City_zone");
    private final static QName _CreatedByDescription_QNAME = new QName("", "Created_by_description");
    private final static QName _OutcomeDescription_QNAME = new QName("", "Outcome_description");
    private final static QName _AttributeValue_QNAME = new QName("", "Attribute_value");
    private final static QName _MessageDeviceDescription_QNAME = new QName("", "Message_device_description");
    private final static QName _PrcParticipantDefId_QNAME = new QName("", "Prc_participant_def_id");
    private final static QName _PriorityDescription_QNAME = new QName("", "Priority_description");
    private final static QName _CustomAttributeDefsCode_QNAME = new QName("", "Custom_attribute_defs_code");
    private final static QName _UnlinkedReasonDescription_QNAME = new QName("", "Unlinked_reason_description");
    private final static QName _ConfigLocationDescription_QNAME = new QName("", "Config_location_description");
    private final static QName _StreetNumber_QNAME = new QName("", "Street_number");
    private final static QName _ResDescription_QNAME = new QName("", "Res_description");
    private final static QName _MessageDeviceCode_QNAME = new QName("", "Message_device_code");
    private final static QName _PrcActivity_QNAME = new QName("", "Prc_activity");
    private final static QName _EmailAddressableInd_QNAME = new QName("", "Email_addressable_ind");
    private final static QName _PrcAttributeDefId_QNAME = new QName("", "Prc_attribute_def_id");
    private final static QName _ResInstanceId_QNAME = new QName("", "Res_instance_id");
    private final static QName _RecordVersion_QNAME = new QName("", "Record_version");
    private final static QName _PrcActivityDefsId_QNAME = new QName("", "Prc_activity_defs_id");
    private final static QName _ParticipantDescription_QNAME = new QName("", "Participant_description");
    private final static QName _PrcHistoricalGeoArea_QNAME = new QName("", "Prc_historical_geo_area");
    private final static QName _StartDate_QNAME = new QName("", "Start_date");
    private final static QName _PrcNumber_QNAME = new QName("", "Prc_number");
    private final static QName _LocationId_QNAME = new QName("", "Location_id");
    private final static QName _BeginResolutionDate_QNAME = new QName("", "Begin_resolution_date");
    private final static QName _NameTypeItemCode_QNAME = new QName("", "Name_type_item_code");
    private final static QName _CategoryCode_QNAME = new QName("", "Category_code");
    private final static QName _StreetTypeCode_QNAME = new QName("", "Street_type_code");
    private final static QName _GeoLocations_QNAME = new QName("", "Geo_locations");
    private final static QName _City_QNAME = new QName("", "City");
    private final static QName _UpdatedByDescription_QNAME = new QName("", "Updated_by_description");
    private final static QName _PrecededPrcActivityId_QNAME = new QName("", "Preceded_prc_activity_id");
    private final static QName _CreationReasonCode_QNAME = new QName("", "Creation_reason_code");
    private final static QName _DurationDaysToComplete_QNAME = new QName("", "Duration_days_to_complete");
    private final static QName _PrcAttributes_QNAME = new QName("", "Prc_attributes");
    private final static QName _DepartureTime_QNAME = new QName("", "Departure_time");
    private final static QName _CreationReasonDescription_QNAME = new QName("", "Creation_reason_description");
    private final static QName _StatusCode_QNAME = new QName("", "Status_code");
    private final static QName _Region_QNAME = new QName("", "Region");
    private final static QName _OwnerGroupCode_QNAME = new QName("", "Owner_group_code");
    private final static QName _MethodReceivedDescription_QNAME = new QName("", "Method_received_description");
    private final static QName _PrefixTypeCode_QNAME = new QName("", "Prefix_type_code");
    private final static QName _District_QNAME = new QName("", "District");
    private final static QName _JurisdictionDescription_QNAME = new QName("", "Jurisdiction_description");
    private final static QName _AssignResId_QNAME = new QName("", "Assign_res_id");
    private final static QName _LinkedPrcNumber_QNAME = new QName("", "Linked_prc_number");
    private final static QName _PrefixDirectionCode_QNAME = new QName("", "Prefix_direction_code");
    private final static QName _ResElectronicAddress_QNAME = new QName("", "Res_electronic_address");
    private final static QName _ResCode_QNAME = new QName("", "Res_code");
    private final static QName _LinkedReasonCode_QNAME = new QName("", "Linked_reason_code");
    private final static QName _StreetName_QNAME = new QName("", "Street_name");
    private final static QName _PrcCode_QNAME = new QName("", "Prc_code");
    private final static QName _YValue_QNAME = new QName("", "Y_value");
    private final static QName _PrcAttribute_QNAME = new QName("", "Prc_attribute");
    private final static QName _AddressTypeCode_QNAME = new QName("", "Address_type_code");
    private final static QName _DescriptionActdef_QNAME = new QName("", "Description_actdef");
    private final static QName _PrcLinkedProcess_QNAME = new QName("", "Prc_linked_process");
    private final static QName _OwnerGroupDescription_QNAME = new QName("", "Owner_group_description");
    private final static QName _PrcParticipant_QNAME = new QName("", "Prc_participant");
    private final static QName _BuildingName_QNAME = new QName("", "Building_name");
    private final static QName _NameField02_QNAME = new QName("", "Name_field_02");
    private final static QName _Floor_QNAME = new QName("", "Floor");
    private final static QName _NameField01_QNAME = new QName("", "Name_field_01");
    private final static QName _ResAttributes_QNAME = new QName("", "Res_attributes");
    private final static QName _NameField06_QNAME = new QName("", "Name_field_06");
    private final static QName _PrcInstanceId_QNAME = new QName("", "Prc_instance_id");
    private final static QName _NameField05_QNAME = new QName("", "Name_field_05");
    private final static QName _ChildPrcInstanceId_QNAME = new QName("", "Child_prc_instance_id");
    private final static QName _NameField04_QNAME = new QName("", "Name_field_04");
    private final static QName _NameField03_QNAME = new QName("", "Name_field_03");
    private final static QName _ManagerResId_QNAME = new QName("", "Manager_res_id");
    private final static QName _CreatedDate_QNAME = new QName("", "Created_date");
    private final static QName _PhoneNumberNoFormat_QNAME = new QName("", "Phone_number_no_format");
    private final static QName _ResInstance_QNAME = new QName("", "Res_instance");
    private final static QName _Extension_QNAME = new QName("", "Extension");
    private final static QName _PrivateInd_QNAME = new QName("", "Private_ind");
    private final static QName _PrcActivityTypeDefsCode_QNAME = new QName("", "Prc_activity_type_defs_code");
    private final static QName _DisplayAddress_QNAME = new QName("", "Display_address");
    private final static QName _DueDate_QNAME = new QName("", "Due_date");
    private final static QName _StatusDate_QNAME = new QName("", "Status_date");
    private final static QName _JurisdictionCode_QNAME = new QName("", "Jurisdiction_code");
    private final static QName _ConfigLocationCode_QNAME = new QName("", "Config_location_code");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: city.baltimore.eip.model.motorola.csr
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link PrcInstance }
     * 
     */
    public PrcInstance createPrcInstance() {
        return new PrcInstance();
    }

    /**
     * Create an instance of {@link PrcAttributesType }
     * 
     */
    public PrcAttributesType createPrcAttributesType() {
        return new PrcAttributesType();
    }

    /**
     * Create an instance of {@link PrcParticipantsType }
     * 
     */
    public PrcParticipantsType createPrcParticipantsType() {
        return new PrcParticipantsType();
    }

    /**
     * Create an instance of {@link PrcActivitiesType }
     * 
     */
    public PrcActivitiesType createPrcActivitiesType() {
        return new PrcActivitiesType();
    }

    /**
     * Create an instance of {@link PrcLinkedProcessesType }
     * 
     */
    public PrcLinkedProcessesType createPrcLinkedProcessesType() {
        return new PrcLinkedProcessesType();
    }

    /**
     * Create an instance of {@link PrcHistoricalGeoAreasType }
     * 
     */
    public PrcHistoricalGeoAreasType createPrcHistoricalGeoAreasType() {
        return new PrcHistoricalGeoAreasType();
    }

    /**
     * Create an instance of {@link LocationsType }
     * 
     */
    public LocationsType createLocationsType() {
        return new LocationsType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link ResElectronicAddressesType }
     * 
     */
    public ResElectronicAddressesType createResElectronicAddressesType() {
        return new ResElectronicAddressesType();
    }

    /**
     * Create an instance of {@link ResPhoneType }
     * 
     */
    public ResPhoneType createResPhoneType() {
        return new ResPhoneType();
    }

    /**
     * Create an instance of {@link ResNameType }
     * 
     */
    public ResNameType createResNameType() {
        return new ResNameType();
    }

    /**
     * Create an instance of {@link ResPhonesType }
     * 
     */
    public ResPhonesType createResPhonesType() {
        return new ResPhonesType();
    }

    /**
     * Create an instance of {@link ResNamesType }
     * 
     */
    public ResNamesType createResNamesType() {
        return new ResNamesType();
    }

    /**
     * Create an instance of {@link ResAttributeType }
     * 
     */
    public ResAttributeType createResAttributeType() {
        return new ResAttributeType();
    }

    /**
     * Create an instance of {@link PrcActivityType }
     * 
     */
    public PrcActivityType createPrcActivityType() {
        return new PrcActivityType();
    }

    /**
     * Create an instance of {@link PrcHistoricalGeoAreaType }
     * 
     */
    public PrcHistoricalGeoAreaType createPrcHistoricalGeoAreaType() {
        return new PrcHistoricalGeoAreaType();
    }

    /**
     * Create an instance of {@link ResElectronicAddressType }
     * 
     */
    public ResElectronicAddressType createResElectronicAddressType() {
        return new ResElectronicAddressType();
    }

    /**
     * Create an instance of {@link ResetParams }
     * 
     */
    public ResetParams createResetParams() {
        return new ResetParams();
    }

    /**
     * Create an instance of {@link PrcAttributeType }
     * 
     */
    public PrcAttributeType createPrcAttributeType() {
        return new PrcAttributeType();
    }

    /**
     * Create an instance of {@link PrcLinkedProcessType }
     * 
     */
    public PrcLinkedProcessType createPrcLinkedProcessType() {
        return new PrcLinkedProcessType();
    }

    /**
     * Create an instance of {@link PrcParticipantType }
     * 
     */
    public PrcParticipantType createPrcParticipantType() {
        return new PrcParticipantType();
    }

    /**
     * Create an instance of {@link ResAttributesType }
     * 
     */
    public ResAttributesType createResAttributesType() {
        return new ResAttributesType();
    }

    /**
     * Create an instance of {@link ResInstanceType }
     * 
     */
    public ResInstanceType createResInstanceType() {
        return new ResInstanceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Country_code")
    public JAXBElement<String> createCountryCode(String value) {
        return new JAXBElement<String>(_CountryCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Display_name")
    public JAXBElement<String> createDisplayName(String value) {
        return new JAXBElement<String>(_DisplayName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Custom_attribute_defs_desc")
    public JAXBElement<String> createCustomAttributeDefsDesc(String value) {
        return new JAXBElement<String>(_CustomAttributeDefsDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Search_display_name")
    public JAXBElement<String> createSearchDisplayName(String value) {
        return new JAXBElement<String>(_SearchDisplayName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Geo_location")
    public JAXBElement<LocationType> createGeoLocation(LocationType value) {
        return new JAXBElement<LocationType>(_GeoLocation_QNAME, LocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Arrival_time")
    public JAXBElement<String> createArrivalTime(String value) {
        return new JAXBElement<String>(_ArrivalTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Parent_prc_instance_id")
    public JAXBElement<BigInteger> createParentPrcInstanceId(BigInteger value) {
        return new JAXBElement<BigInteger>(_ParentPrcInstanceId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Phone_description")
    public JAXBElement<String> createPhoneDescription(String value) {
        return new JAXBElement<String>(_PhoneDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Phone_number")
    public JAXBElement<String> createPhoneNumber(String value) {
        return new JAXBElement<String>(_PhoneNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Electronic_address")
    public JAXBElement<String> createElectronicAddress(String value) {
        return new JAXBElement<String>(_ElectronicAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Method_received_code")
    public JAXBElement<String> createMethodReceivedCode(String value) {
        return new JAXBElement<String>(_MethodReceivedCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Location_details")
    public JAXBElement<String> createLocationDetails(String value) {
        return new JAXBElement<String>(_LocationDetails_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_description")
    public JAXBElement<String> createPrcDescription(String value) {
        return new JAXBElement<String>(_PrcDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Status_description")
    public JAXBElement<String> createStatusDescription(String value) {
        return new JAXBElement<String>(_StatusDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Attribute_datatype_code")
    public JAXBElement<String> createAttributeDatatypeCode(String value) {
        return new JAXBElement<String>(_AttributeDatatypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Attribute_codes")
    public JAXBElement<String> createAttributeCodes(String value) {
        return new JAXBElement<String>(_AttributeCodes_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Linked_reason_description")
    public JAXBElement<String> createLinkedReasonDescription(String value) {
        return new JAXBElement<String>(_LinkedReasonDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Unit_number")
    public JAXBElement<String> createUnitNumber(String value) {
        return new JAXBElement<String>(_UnitNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Config_location_value")
    public JAXBElement<String> createConfigLocationValue(String value) {
        return new JAXBElement<String>(_ConfigLocationValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "X_value")
    public JAXBElement<BigDecimal> createXValue(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_XValue_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Type_custom_attribute_id")
    public JAXBElement<BigInteger> createTypeCustomAttributeId(BigInteger value) {
        return new JAXBElement<BigInteger>(_TypeCustomAttributeId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResElectronicAddressesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Res_electronic_addresses")
    public JAXBElement<ResElectronicAddressesType> createResElectronicAddresses(ResElectronicAddressesType value) {
        return new JAXBElement<ResElectronicAddressesType>(_ResElectronicAddresses_QNAME, ResElectronicAddressesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Phone_code")
    public JAXBElement<String> createPhoneCode(String value) {
        return new JAXBElement<String>(_PhoneCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Electronic_address_description")
    public JAXBElement<String> createElectronicAddressDescription(String value) {
        return new JAXBElement<String>(_ElectronicAddressDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrcParticipantsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_participants")
    public JAXBElement<PrcParticipantsType> createPrcParticipants(PrcParticipantsType value) {
        return new JAXBElement<PrcParticipantsType>(_PrcParticipants_QNAME, PrcParticipantsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Parent_activity_id")
    public JAXBElement<BigInteger> createParentActivityId(BigInteger value) {
        return new JAXBElement<BigInteger>(_ParentActivityId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Details")
    public JAXBElement<String> createDetails(String value) {
        return new JAXBElement<String>(_Details_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Priority_code")
    public JAXBElement<String> createPriorityCode(String value) {
        return new JAXBElement<String>(_PriorityCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Completed_date")
    public JAXBElement<String> createCompletedDate(String value) {
        return new JAXBElement<String>(_CompletedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Id")
    public JAXBElement<BigInteger> createId(BigInteger value) {
        return new JAXBElement<BigInteger>(_Id_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrcActivitiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_activities")
    public JAXBElement<PrcActivitiesType> createPrcActivities(PrcActivitiesType value) {
        return new JAXBElement<PrcActivitiesType>(_PrcActivities_QNAME, PrcActivitiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Stop_date")
    public JAXBElement<String> createStopDate(String value) {
        return new JAXBElement<String>(_StopDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Related_record_id")
    public JAXBElement<BigInteger> createRelatedRecordId(BigInteger value) {
        return new JAXBElement<BigInteger>(_RelatedRecordId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Updated_date")
    public JAXBElement<String> createUpdatedDate(String value) {
        return new JAXBElement<String>(_UpdatedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Electronic_address_code")
    public JAXBElement<String> createElectronicAddressCode(String value) {
        return new JAXBElement<String>(_ElectronicAddressCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResPhoneType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Res_phone")
    public JAXBElement<ResPhoneType> createResPhone(ResPhoneType value) {
        return new JAXBElement<ResPhoneType>(_ResPhone_QNAME, ResPhoneType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Linked_prc_code")
    public JAXBElement<String> createLinkedPrcCode(String value) {
        return new JAXBElement<String>(_LinkedPrcCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Res_name")
    public JAXBElement<ResNameType> createResName(ResNameType value) {
        return new JAXBElement<ResNameType>(_ResName_QNAME, ResNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Suffix_direction_code")
    public JAXBElement<String> createSuffixDirectionCode(String value) {
        return new JAXBElement<String>(_SuffixDirectionCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Participant_code")
    public JAXBElement<String> createParticipantCode(String value) {
        return new JAXBElement<String>(_ParticipantCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResPhonesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Res_phones")
    public JAXBElement<ResPhonesType> createResPhones(ResPhonesType value) {
        return new JAXBElement<ResPhonesType>(_ResPhones_QNAME, ResPhonesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Updated_by")
    public JAXBElement<BigInteger> createUpdatedBy(BigInteger value) {
        return new JAXBElement<BigInteger>(_UpdatedBy_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrcHistoricalGeoAreasType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_historical_geo_areas")
    public JAXBElement<PrcHistoricalGeoAreasType> createPrcHistoricalGeoAreas(PrcHistoricalGeoAreasType value) {
        return new JAXBElement<PrcHistoricalGeoAreasType>(_PrcHistoricalGeoAreas_QNAME, PrcHistoricalGeoAreasType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResNamesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Res_names")
    public JAXBElement<ResNamesType> createResNames(ResNamesType value) {
        return new JAXBElement<ResNamesType>(_ResNames_QNAME, ResNamesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResAttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Res_attribute")
    public JAXBElement<ResAttributeType> createResAttribute(ResAttributeType value) {
        return new JAXBElement<ResAttributeType>(_ResAttribute_QNAME, ResAttributeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Is_source_of_prc_ind")
    public JAXBElement<String> createIsSourceOfPrcInd(String value) {
        return new JAXBElement<String>(_IsSourceOfPrcInd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Outcome_code")
    public JAXBElement<String> createOutcomeCode(String value) {
        return new JAXBElement<String>(_OutcomeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Created_by")
    public JAXBElement<BigInteger> createCreatedBy(BigInteger value) {
        return new JAXBElement<BigInteger>(_CreatedBy_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Unlinked_reason_code")
    public JAXBElement<String> createUnlinkedReasonCode(String value) {
        return new JAXBElement<String>(_UnlinkedReasonCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name_type_item_description")
    public JAXBElement<String> createNameTypeItemDescription(String value) {
        return new JAXBElement<String>(_NameTypeItemDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrcLinkedProcessesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_linked_processes")
    public JAXBElement<PrcLinkedProcessesType> createPrcLinkedProcesses(PrcLinkedProcessesType value) {
        return new JAXBElement<PrcLinkedProcessesType>(_PrcLinkedProcesses_QNAME, PrcLinkedProcessesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Related_table_code")
    public JAXBElement<String> createRelatedTableCode(String value) {
        return new JAXBElement<String>(_RelatedTableCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Unlinked_date")
    public JAXBElement<String> createUnlinkedDate(String value) {
        return new JAXBElement<String>(_UnlinkedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "City_zone")
    public JAXBElement<String> createCityZone(String value) {
        return new JAXBElement<String>(_CityZone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Created_by_description")
    public JAXBElement<String> createCreatedByDescription(String value) {
        return new JAXBElement<String>(_CreatedByDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Outcome_description")
    public JAXBElement<String> createOutcomeDescription(String value) {
        return new JAXBElement<String>(_OutcomeDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Attribute_value")
    public JAXBElement<String> createAttributeValue(String value) {
        return new JAXBElement<String>(_AttributeValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Message_device_description")
    public JAXBElement<String> createMessageDeviceDescription(String value) {
        return new JAXBElement<String>(_MessageDeviceDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_participant_def_id")
    public JAXBElement<BigInteger> createPrcParticipantDefId(BigInteger value) {
        return new JAXBElement<BigInteger>(_PrcParticipantDefId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Priority_description")
    public JAXBElement<String> createPriorityDescription(String value) {
        return new JAXBElement<String>(_PriorityDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Custom_attribute_defs_code")
    public JAXBElement<String> createCustomAttributeDefsCode(String value) {
        return new JAXBElement<String>(_CustomAttributeDefsCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Unlinked_reason_description")
    public JAXBElement<String> createUnlinkedReasonDescription(String value) {
        return new JAXBElement<String>(_UnlinkedReasonDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Config_location_description")
    public JAXBElement<String> createConfigLocationDescription(String value) {
        return new JAXBElement<String>(_ConfigLocationDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Street_number")
    public JAXBElement<String> createStreetNumber(String value) {
        return new JAXBElement<String>(_StreetNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Res_description")
    public JAXBElement<String> createResDescription(String value) {
        return new JAXBElement<String>(_ResDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Message_device_code")
    public JAXBElement<String> createMessageDeviceCode(String value) {
        return new JAXBElement<String>(_MessageDeviceCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrcActivityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_activity")
    public JAXBElement<PrcActivityType> createPrcActivity(PrcActivityType value) {
        return new JAXBElement<PrcActivityType>(_PrcActivity_QNAME, PrcActivityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Email_addressable_ind")
    public JAXBElement<String> createEmailAddressableInd(String value) {
        return new JAXBElement<String>(_EmailAddressableInd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_attribute_def_id")
    public JAXBElement<BigInteger> createPrcAttributeDefId(BigInteger value) {
        return new JAXBElement<BigInteger>(_PrcAttributeDefId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Res_instance_id")
    public JAXBElement<BigInteger> createResInstanceId(BigInteger value) {
        return new JAXBElement<BigInteger>(_ResInstanceId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Record_version")
    public JAXBElement<BigInteger> createRecordVersion(BigInteger value) {
        return new JAXBElement<BigInteger>(_RecordVersion_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_activity_defs_id")
    public JAXBElement<BigInteger> createPrcActivityDefsId(BigInteger value) {
        return new JAXBElement<BigInteger>(_PrcActivityDefsId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Participant_description")
    public JAXBElement<String> createParticipantDescription(String value) {
        return new JAXBElement<String>(_ParticipantDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrcHistoricalGeoAreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_historical_geo_area")
    public JAXBElement<PrcHistoricalGeoAreaType> createPrcHistoricalGeoArea(PrcHistoricalGeoAreaType value) {
        return new JAXBElement<PrcHistoricalGeoAreaType>(_PrcHistoricalGeoArea_QNAME, PrcHistoricalGeoAreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Start_date")
    public JAXBElement<String> createStartDate(String value) {
        return new JAXBElement<String>(_StartDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_number")
    public JAXBElement<String> createPrcNumber(String value) {
        return new JAXBElement<String>(_PrcNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Location_id")
    public JAXBElement<BigInteger> createLocationId(BigInteger value) {
        return new JAXBElement<BigInteger>(_LocationId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Begin_resolution_date")
    public JAXBElement<String> createBeginResolutionDate(String value) {
        return new JAXBElement<String>(_BeginResolutionDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name_type_item_code")
    public JAXBElement<String> createNameTypeItemCode(String value) {
        return new JAXBElement<String>(_NameTypeItemCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Category_code")
    public JAXBElement<String> createCategoryCode(String value) {
        return new JAXBElement<String>(_CategoryCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Street_type_code")
    public JAXBElement<String> createStreetTypeCode(String value) {
        return new JAXBElement<String>(_StreetTypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Geo_locations")
    public JAXBElement<LocationsType> createGeoLocations(LocationsType value) {
        return new JAXBElement<LocationsType>(_GeoLocations_QNAME, LocationsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "City")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Updated_by_description")
    public JAXBElement<String> createUpdatedByDescription(String value) {
        return new JAXBElement<String>(_UpdatedByDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Preceded_prc_activity_id")
    public JAXBElement<BigInteger> createPrecededPrcActivityId(BigInteger value) {
        return new JAXBElement<BigInteger>(_PrecededPrcActivityId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Creation_reason_code")
    public JAXBElement<String> createCreationReasonCode(String value) {
        return new JAXBElement<String>(_CreationReasonCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Duration_days_to_complete")
    public JAXBElement<BigDecimal> createDurationDaysToComplete(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DurationDaysToComplete_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrcAttributesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_attributes")
    public JAXBElement<PrcAttributesType> createPrcAttributes(PrcAttributesType value) {
        return new JAXBElement<PrcAttributesType>(_PrcAttributes_QNAME, PrcAttributesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Departure_time")
    public JAXBElement<String> createDepartureTime(String value) {
        return new JAXBElement<String>(_DepartureTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Creation_reason_description")
    public JAXBElement<String> createCreationReasonDescription(String value) {
        return new JAXBElement<String>(_CreationReasonDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Status_code")
    public JAXBElement<String> createStatusCode(String value) {
        return new JAXBElement<String>(_StatusCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Region")
    public JAXBElement<String> createRegion(String value) {
        return new JAXBElement<String>(_Region_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Owner_group_code")
    public JAXBElement<String> createOwnerGroupCode(String value) {
        return new JAXBElement<String>(_OwnerGroupCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Method_received_description")
    public JAXBElement<String> createMethodReceivedDescription(String value) {
        return new JAXBElement<String>(_MethodReceivedDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prefix_type_code")
    public JAXBElement<String> createPrefixTypeCode(String value) {
        return new JAXBElement<String>(_PrefixTypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "District")
    public JAXBElement<String> createDistrict(String value) {
        return new JAXBElement<String>(_District_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Jurisdiction_description")
    public JAXBElement<String> createJurisdictionDescription(String value) {
        return new JAXBElement<String>(_JurisdictionDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Assign_res_id")
    public JAXBElement<BigInteger> createAssignResId(BigInteger value) {
        return new JAXBElement<BigInteger>(_AssignResId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Linked_prc_number")
    public JAXBElement<String> createLinkedPrcNumber(String value) {
        return new JAXBElement<String>(_LinkedPrcNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prefix_direction_code")
    public JAXBElement<String> createPrefixDirectionCode(String value) {
        return new JAXBElement<String>(_PrefixDirectionCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResElectronicAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Res_electronic_address")
    public JAXBElement<ResElectronicAddressType> createResElectronicAddress(ResElectronicAddressType value) {
        return new JAXBElement<ResElectronicAddressType>(_ResElectronicAddress_QNAME, ResElectronicAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Res_code")
    public JAXBElement<String> createResCode(String value) {
        return new JAXBElement<String>(_ResCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Linked_reason_code")
    public JAXBElement<String> createLinkedReasonCode(String value) {
        return new JAXBElement<String>(_LinkedReasonCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Street_name")
    public JAXBElement<String> createStreetName(String value) {
        return new JAXBElement<String>(_StreetName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_code")
    public JAXBElement<String> createPrcCode(String value) {
        return new JAXBElement<String>(_PrcCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Y_value")
    public JAXBElement<BigDecimal> createYValue(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_YValue_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrcAttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_attribute")
    public JAXBElement<PrcAttributeType> createPrcAttribute(PrcAttributeType value) {
        return new JAXBElement<PrcAttributeType>(_PrcAttribute_QNAME, PrcAttributeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address_type_code")
    public JAXBElement<String> createAddressTypeCode(String value) {
        return new JAXBElement<String>(_AddressTypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Description_actdef")
    public JAXBElement<String> createDescriptionActdef(String value) {
        return new JAXBElement<String>(_DescriptionActdef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrcLinkedProcessType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_linked_process")
    public JAXBElement<PrcLinkedProcessType> createPrcLinkedProcess(PrcLinkedProcessType value) {
        return new JAXBElement<PrcLinkedProcessType>(_PrcLinkedProcess_QNAME, PrcLinkedProcessType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Owner_group_description")
    public JAXBElement<String> createOwnerGroupDescription(String value) {
        return new JAXBElement<String>(_OwnerGroupDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrcParticipantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_participant")
    public JAXBElement<PrcParticipantType> createPrcParticipant(PrcParticipantType value) {
        return new JAXBElement<PrcParticipantType>(_PrcParticipant_QNAME, PrcParticipantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Building_name")
    public JAXBElement<String> createBuildingName(String value) {
        return new JAXBElement<String>(_BuildingName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name_field_02")
    public JAXBElement<String> createNameField02(String value) {
        return new JAXBElement<String>(_NameField02_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Floor")
    public JAXBElement<String> createFloor(String value) {
        return new JAXBElement<String>(_Floor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name_field_01")
    public JAXBElement<String> createNameField01(String value) {
        return new JAXBElement<String>(_NameField01_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResAttributesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Res_attributes")
    public JAXBElement<ResAttributesType> createResAttributes(ResAttributesType value) {
        return new JAXBElement<ResAttributesType>(_ResAttributes_QNAME, ResAttributesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name_field_06")
    public JAXBElement<String> createNameField06(String value) {
        return new JAXBElement<String>(_NameField06_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_instance_id")
    public JAXBElement<BigInteger> createPrcInstanceId(BigInteger value) {
        return new JAXBElement<BigInteger>(_PrcInstanceId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name_field_05")
    public JAXBElement<String> createNameField05(String value) {
        return new JAXBElement<String>(_NameField05_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Child_prc_instance_id")
    public JAXBElement<BigInteger> createChildPrcInstanceId(BigInteger value) {
        return new JAXBElement<BigInteger>(_ChildPrcInstanceId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name_field_04")
    public JAXBElement<String> createNameField04(String value) {
        return new JAXBElement<String>(_NameField04_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name_field_03")
    public JAXBElement<String> createNameField03(String value) {
        return new JAXBElement<String>(_NameField03_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Manager_res_id")
    public JAXBElement<BigInteger> createManagerResId(BigInteger value) {
        return new JAXBElement<BigInteger>(_ManagerResId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Created_date")
    public JAXBElement<String> createCreatedDate(String value) {
        return new JAXBElement<String>(_CreatedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Phone_number_no_format")
    public JAXBElement<String> createPhoneNumberNoFormat(String value) {
        return new JAXBElement<String>(_PhoneNumberNoFormat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Res_instance")
    public JAXBElement<ResInstanceType> createResInstance(ResInstanceType value) {
        return new JAXBElement<ResInstanceType>(_ResInstance_QNAME, ResInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Extension")
    public JAXBElement<String> createExtension(String value) {
        return new JAXBElement<String>(_Extension_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Private_ind")
    public JAXBElement<String> createPrivateInd(String value) {
        return new JAXBElement<String>(_PrivateInd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Prc_activity_type_defs_code")
    public JAXBElement<String> createPrcActivityTypeDefsCode(String value) {
        return new JAXBElement<String>(_PrcActivityTypeDefsCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Display_address")
    public JAXBElement<String> createDisplayAddress(String value) {
        return new JAXBElement<String>(_DisplayAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Due_date")
    public JAXBElement<String> createDueDate(String value) {
        return new JAXBElement<String>(_DueDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Status_date")
    public JAXBElement<String> createStatusDate(String value) {
        return new JAXBElement<String>(_StatusDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Jurisdiction_code")
    public JAXBElement<String> createJurisdictionCode(String value) {
        return new JAXBElement<String>(_JurisdictionCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Config_location_code")
    public JAXBElement<String> createConfigLocationCode(String value) {
        return new JAXBElement<String>(_ConfigLocationCode_QNAME, String.class, null, value);
    }

}
