//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 04:00:13 PM EST 
//


package city.baltimore.eip.model.motorola.csr;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for prcAttributeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="prcAttributeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Id" minOccurs="0"/>
 *         &lt;element ref="{}Prc_attribute_def_id" minOccurs="0"/>
 *         &lt;element ref="{}Prc_instance_id" minOccurs="0"/>
 *         &lt;element ref="{}Attribute_value" minOccurs="0"/>
 *         &lt;element ref="{}Attribute_codes" minOccurs="0"/>
 *         &lt;element ref="{}Created_by" minOccurs="0"/>
 *         &lt;element ref="{}Created_date" minOccurs="0"/>
 *         &lt;element ref="{}Updated_by" minOccurs="0"/>
 *         &lt;element ref="{}Updated_date" minOccurs="0"/>
 *         &lt;element ref="{}Record_version" minOccurs="0"/>
 *         &lt;element ref="{}Prc_code" minOccurs="0"/>
 *         &lt;element ref="{}Attribute_datatype_code" minOccurs="0"/>
 *         &lt;element ref="{}Custom_attribute_defs_code" minOccurs="0"/>
 *         &lt;element ref="{}Custom_attribute_defs_desc" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "prcAttributeType", propOrder = {
    "id",
    "prcAttributeDefId",
    "prcInstanceId",
    "attributeValue",
    "attributeCodes",
    "createdBy",
    "createdDate",
    "updatedBy",
    "updatedDate",
    "recordVersion",
    "prcCode",
    "attributeDatatypeCode",
    "customAttributeDefsCode",
    "customAttributeDefsDesc"
})
public class PrcAttributeType {

    @XmlElement(name = "Id")
    protected BigInteger id;
    @XmlElement(name = "Prc_attribute_def_id")
    protected BigInteger prcAttributeDefId;
    @XmlElement(name = "Prc_instance_id")
    protected BigInteger prcInstanceId;
    @XmlElement(name = "Attribute_value")
    protected String attributeValue;
    @XmlElement(name = "Attribute_codes")
    protected String attributeCodes;
    @XmlElement(name = "Created_by")
    protected BigInteger createdBy;
    @XmlElement(name = "Created_date")
    protected String createdDate;
    @XmlElement(name = "Updated_by")
    protected BigInteger updatedBy;
    @XmlElement(name = "Updated_date")
    protected String updatedDate;
    @XmlElement(name = "Record_version")
    protected BigInteger recordVersion;
    @XmlElement(name = "Prc_code")
    protected String prcCode;
    @XmlElement(name = "Attribute_datatype_code")
    protected String attributeDatatypeCode;
    @XmlElement(name = "Custom_attribute_defs_code")
    protected String customAttributeDefsCode;
    @XmlElement(name = "Custom_attribute_defs_desc")
    protected String customAttributeDefsDesc;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the prcAttributeDefId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrcAttributeDefId() {
        return prcAttributeDefId;
    }

    /**
     * Sets the value of the prcAttributeDefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrcAttributeDefId(BigInteger value) {
        this.prcAttributeDefId = value;
    }

    /**
     * Gets the value of the prcInstanceId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrcInstanceId() {
        return prcInstanceId;
    }

    /**
     * Sets the value of the prcInstanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrcInstanceId(BigInteger value) {
        this.prcInstanceId = value;
    }

    /**
     * Gets the value of the attributeValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeValue() {
        return attributeValue;
    }

    /**
     * Sets the value of the attributeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeValue(String value) {
        this.attributeValue = value;
    }

    /**
     * Gets the value of the attributeCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeCodes() {
        return attributeCodes;
    }

    /**
     * Sets the value of the attributeCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeCodes(String value) {
        this.attributeCodes = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCreatedBy(BigInteger value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDate(String value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUpdatedBy(BigInteger value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the updatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedDate() {
        return updatedDate;
    }

    /**
     * Sets the value of the updatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedDate(String value) {
        this.updatedDate = value;
    }

    /**
     * Gets the value of the recordVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecordVersion() {
        return recordVersion;
    }

    /**
     * Sets the value of the recordVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecordVersion(BigInteger value) {
        this.recordVersion = value;
    }

    /**
     * Gets the value of the prcCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrcCode() {
        return prcCode;
    }

    /**
     * Sets the value of the prcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrcCode(String value) {
        this.prcCode = value;
    }

    /**
     * Gets the value of the attributeDatatypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeDatatypeCode() {
        return attributeDatatypeCode;
    }

    /**
     * Sets the value of the attributeDatatypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeDatatypeCode(String value) {
        this.attributeDatatypeCode = value;
    }

    /**
     * Gets the value of the customAttributeDefsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomAttributeDefsCode() {
        return customAttributeDefsCode;
    }

    /**
     * Sets the value of the customAttributeDefsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomAttributeDefsCode(String value) {
        this.customAttributeDefsCode = value;
    }

    /**
     * Gets the value of the customAttributeDefsDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomAttributeDefsDesc() {
        return customAttributeDefsDesc;
    }

    /**
     * Sets the value of the customAttributeDefsDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomAttributeDefsDesc(String value) {
        this.customAttributeDefsDesc = value;
    }

}
