//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 04:00:13 PM EST 
//


package city.baltimore.eip.model.motorola.csr;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for prcActivityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="prcActivityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Id" minOccurs="0"/>
 *         &lt;element ref="{}Prc_instance_id" minOccurs="0"/>
 *         &lt;element ref="{}Assign_res_id" minOccurs="0"/>
 *         &lt;element ref="{}Outcome_code" minOccurs="0"/>
 *         &lt;element ref="{}Outcome_description" minOccurs="0"/>
 *         &lt;element ref="{}Prc_activity_defs_id" minOccurs="0"/>
 *         &lt;element ref="{}Completed_date" minOccurs="0"/>
 *         &lt;element ref="{}Details" minOccurs="0"/>
 *         &lt;element ref="{}Preceded_prc_activity_id" minOccurs="0"/>
 *         &lt;element ref="{}Arrival_time" minOccurs="0"/>
 *         &lt;element ref="{}Departure_time" minOccurs="0"/>
 *         &lt;element ref="{}Due_date" minOccurs="0"/>
 *         &lt;element ref="{}Created_by" minOccurs="0"/>
 *         &lt;element ref="{}Created_date" minOccurs="0"/>
 *         &lt;element ref="{}Updated_by" minOccurs="0"/>
 *         &lt;element ref="{}Updated_date" minOccurs="0"/>
 *         &lt;element ref="{}Record_version" minOccurs="0"/>
 *         &lt;element ref="{}Prc_activity_type_defs_code" minOccurs="0"/>
 *         &lt;element ref="{}Description_actdef" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "prcActivityType", propOrder = {
    "id",
    "prcInstanceId",
    "assignResId",
    "outcomeCode",
    "outcomeDescription",
    "prcActivityDefsId",
    "completedDate",
    "details",
    "precededPrcActivityId",
    "arrivalTime",
    "departureTime",
    "dueDate",
    "createdBy",
    "createdDate",
    "updatedBy",
    "updatedDate",
    "recordVersion",
    "prcActivityTypeDefsCode",
    "descriptionActdef"
})
public class PrcActivityType {

    @XmlElement(name = "Id")
    protected BigInteger id;
    @XmlElement(name = "Prc_instance_id")
    protected BigInteger prcInstanceId;
    @XmlElement(name = "Assign_res_id")
    protected BigInteger assignResId;
    @XmlElement(name = "Outcome_code")
    protected String outcomeCode;
    @XmlElement(name = "Outcome_description")
    protected String outcomeDescription;
    @XmlElement(name = "Prc_activity_defs_id")
    protected BigInteger prcActivityDefsId;
    @XmlElement(name = "Completed_date")
    protected String completedDate;
    @XmlElement(name = "Details")
    protected String details;
    @XmlElement(name = "Preceded_prc_activity_id")
    protected BigInteger precededPrcActivityId;
    @XmlElement(name = "Arrival_time")
    protected String arrivalTime;
    @XmlElement(name = "Departure_time")
    protected String departureTime;
    @XmlElement(name = "Due_date")
    protected String dueDate;
    @XmlElement(name = "Created_by")
    protected BigInteger createdBy;
    @XmlElement(name = "Created_date")
    protected String createdDate;
    @XmlElement(name = "Updated_by")
    protected BigInteger updatedBy;
    @XmlElement(name = "Updated_date")
    protected String updatedDate;
    @XmlElement(name = "Record_version")
    protected BigInteger recordVersion;
    @XmlElement(name = "Prc_activity_type_defs_code")
    protected String prcActivityTypeDefsCode;
    @XmlElement(name = "Description_actdef")
    protected String descriptionActdef;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the prcInstanceId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrcInstanceId() {
        return prcInstanceId;
    }

    /**
     * Sets the value of the prcInstanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrcInstanceId(BigInteger value) {
        this.prcInstanceId = value;
    }

    /**
     * Gets the value of the assignResId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAssignResId() {
        return assignResId;
    }

    /**
     * Sets the value of the assignResId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAssignResId(BigInteger value) {
        this.assignResId = value;
    }

    /**
     * Gets the value of the outcomeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutcomeCode() {
        return outcomeCode;
    }

    /**
     * Sets the value of the outcomeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutcomeCode(String value) {
        this.outcomeCode = value;
    }

    /**
     * Gets the value of the outcomeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutcomeDescription() {
        return outcomeDescription;
    }

    /**
     * Sets the value of the outcomeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutcomeDescription(String value) {
        this.outcomeDescription = value;
    }

    /**
     * Gets the value of the prcActivityDefsId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrcActivityDefsId() {
        return prcActivityDefsId;
    }

    /**
     * Sets the value of the prcActivityDefsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrcActivityDefsId(BigInteger value) {
        this.prcActivityDefsId = value;
    }

    /**
     * Gets the value of the completedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompletedDate() {
        return completedDate;
    }

    /**
     * Sets the value of the completedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompletedDate(String value) {
        this.completedDate = value;
    }

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetails(String value) {
        this.details = value;
    }

    /**
     * Gets the value of the precededPrcActivityId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrecededPrcActivityId() {
        return precededPrcActivityId;
    }

    /**
     * Sets the value of the precededPrcActivityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrecededPrcActivityId(BigInteger value) {
        this.precededPrcActivityId = value;
    }

    /**
     * Gets the value of the arrivalTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalTime() {
        return arrivalTime;
    }

    /**
     * Sets the value of the arrivalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalTime(String value) {
        this.arrivalTime = value;
    }

    /**
     * Gets the value of the departureTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureTime() {
        return departureTime;
    }

    /**
     * Sets the value of the departureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureTime(String value) {
        this.departureTime = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueDate(String value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCreatedBy(BigInteger value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDate(String value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUpdatedBy(BigInteger value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the updatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedDate() {
        return updatedDate;
    }

    /**
     * Sets the value of the updatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedDate(String value) {
        this.updatedDate = value;
    }

    /**
     * Gets the value of the recordVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecordVersion() {
        return recordVersion;
    }

    /**
     * Sets the value of the recordVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecordVersion(BigInteger value) {
        this.recordVersion = value;
    }

    /**
     * Gets the value of the prcActivityTypeDefsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrcActivityTypeDefsCode() {
        return prcActivityTypeDefsCode;
    }

    /**
     * Sets the value of the prcActivityTypeDefsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrcActivityTypeDefsCode(String value) {
        this.prcActivityTypeDefsCode = value;
    }

    /**
     * Gets the value of the descriptionActdef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescriptionActdef() {
        return descriptionActdef;
    }

    /**
     * Sets the value of the descriptionActdef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescriptionActdef(String value) {
        this.descriptionActdef = value;
    }

}
