//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 04:00:13 PM EST 
//


package city.baltimore.eip.model.motorola.csr;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for prcLinkedProcessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="prcLinkedProcessType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Id" minOccurs="0"/>
 *         &lt;element ref="{}Child_prc_instance_id" minOccurs="0"/>
 *         &lt;element ref="{}Parent_prc_instance_id" minOccurs="0"/>
 *         &lt;element ref="{}Linked_prc_number" minOccurs="0"/>
 *         &lt;element ref="{}Linked_prc_code" minOccurs="0"/>
 *         &lt;element ref="{}Unlinked_reason_code" minOccurs="0"/>
 *         &lt;element ref="{}Unlinked_reason_description" minOccurs="0"/>
 *         &lt;element ref="{}Linked_reason_code" minOccurs="0"/>
 *         &lt;element ref="{}Linked_reason_description" minOccurs="0"/>
 *         &lt;element ref="{}Parent_activity_id" minOccurs="0"/>
 *         &lt;element ref="{}Unlinked_date" minOccurs="0"/>
 *         &lt;element ref="{}Created_by" minOccurs="0"/>
 *         &lt;element ref="{}Created_date" minOccurs="0"/>
 *         &lt;element ref="{}Updated_by" minOccurs="0"/>
 *         &lt;element ref="{}Updated_date" minOccurs="0"/>
 *         &lt;element ref="{}Record_version" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "prcLinkedProcessType", propOrder = {
    "id",
    "childPrcInstanceId",
    "parentPrcInstanceId",
    "linkedPrcNumber",
    "linkedPrcCode",
    "unlinkedReasonCode",
    "unlinkedReasonDescription",
    "linkedReasonCode",
    "linkedReasonDescription",
    "parentActivityId",
    "unlinkedDate",
    "createdBy",
    "createdDate",
    "updatedBy",
    "updatedDate",
    "recordVersion"
})
public class PrcLinkedProcessType {

    @XmlElement(name = "Id")
    protected BigInteger id;
    @XmlElement(name = "Child_prc_instance_id")
    protected BigInteger childPrcInstanceId;
    @XmlElement(name = "Parent_prc_instance_id")
    protected BigInteger parentPrcInstanceId;
    @XmlElement(name = "Linked_prc_number")
    protected String linkedPrcNumber;
    @XmlElement(name = "Linked_prc_code")
    protected String linkedPrcCode;
    @XmlElement(name = "Unlinked_reason_code")
    protected String unlinkedReasonCode;
    @XmlElement(name = "Unlinked_reason_description")
    protected String unlinkedReasonDescription;
    @XmlElement(name = "Linked_reason_code")
    protected String linkedReasonCode;
    @XmlElement(name = "Linked_reason_description")
    protected String linkedReasonDescription;
    @XmlElement(name = "Parent_activity_id")
    protected BigInteger parentActivityId;
    @XmlElement(name = "Unlinked_date")
    protected String unlinkedDate;
    @XmlElement(name = "Created_by")
    protected BigInteger createdBy;
    @XmlElement(name = "Created_date")
    protected String createdDate;
    @XmlElement(name = "Updated_by")
    protected BigInteger updatedBy;
    @XmlElement(name = "Updated_date")
    protected String updatedDate;
    @XmlElement(name = "Record_version")
    protected BigInteger recordVersion;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the childPrcInstanceId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChildPrcInstanceId() {
        return childPrcInstanceId;
    }

    /**
     * Sets the value of the childPrcInstanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChildPrcInstanceId(BigInteger value) {
        this.childPrcInstanceId = value;
    }

    /**
     * Gets the value of the parentPrcInstanceId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParentPrcInstanceId() {
        return parentPrcInstanceId;
    }

    /**
     * Sets the value of the parentPrcInstanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParentPrcInstanceId(BigInteger value) {
        this.parentPrcInstanceId = value;
    }

    /**
     * Gets the value of the linkedPrcNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedPrcNumber() {
        return linkedPrcNumber;
    }

    /**
     * Sets the value of the linkedPrcNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedPrcNumber(String value) {
        this.linkedPrcNumber = value;
    }

    /**
     * Gets the value of the linkedPrcCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedPrcCode() {
        return linkedPrcCode;
    }

    /**
     * Sets the value of the linkedPrcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedPrcCode(String value) {
        this.linkedPrcCode = value;
    }

    /**
     * Gets the value of the unlinkedReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnlinkedReasonCode() {
        return unlinkedReasonCode;
    }

    /**
     * Sets the value of the unlinkedReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnlinkedReasonCode(String value) {
        this.unlinkedReasonCode = value;
    }

    /**
     * Gets the value of the unlinkedReasonDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnlinkedReasonDescription() {
        return unlinkedReasonDescription;
    }

    /**
     * Sets the value of the unlinkedReasonDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnlinkedReasonDescription(String value) {
        this.unlinkedReasonDescription = value;
    }

    /**
     * Gets the value of the linkedReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedReasonCode() {
        return linkedReasonCode;
    }

    /**
     * Sets the value of the linkedReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedReasonCode(String value) {
        this.linkedReasonCode = value;
    }

    /**
     * Gets the value of the linkedReasonDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedReasonDescription() {
        return linkedReasonDescription;
    }

    /**
     * Sets the value of the linkedReasonDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedReasonDescription(String value) {
        this.linkedReasonDescription = value;
    }

    /**
     * Gets the value of the parentActivityId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParentActivityId() {
        return parentActivityId;
    }

    /**
     * Sets the value of the parentActivityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParentActivityId(BigInteger value) {
        this.parentActivityId = value;
    }

    /**
     * Gets the value of the unlinkedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnlinkedDate() {
        return unlinkedDate;
    }

    /**
     * Sets the value of the unlinkedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnlinkedDate(String value) {
        this.unlinkedDate = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCreatedBy(BigInteger value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDate(String value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUpdatedBy(BigInteger value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the updatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedDate() {
        return updatedDate;
    }

    /**
     * Sets the value of the updatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedDate(String value) {
        this.updatedDate = value;
    }

    /**
     * Gets the value of the recordVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecordVersion() {
        return recordVersion;
    }

    /**
     * Sets the value of the recordVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecordVersion(BigInteger value) {
        this.recordVersion = value;
    }

}
