//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 04:00:13 PM EST 
//


package city.baltimore.eip.model.motorola.csr;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import city.baltimore.eip.model.CsrElement;


/**
 * <p>Java class for resElectronicAddressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resElectronicAddressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Id" minOccurs="0"/>
 *         &lt;element ref="{}Res_instance_id" minOccurs="0"/>
 *         &lt;element ref="{}Electronic_address_code" minOccurs="0"/>
 *         &lt;element ref="{}Electronic_address_description" minOccurs="0"/>
 *         &lt;element ref="{}Message_device_code" minOccurs="0"/>
 *         &lt;element ref="{}Message_device_description" minOccurs="0"/>
 *         &lt;element ref="{}Electronic_address" minOccurs="0"/>
 *         &lt;element ref="{}Email_addressable_ind" minOccurs="0"/>
 *         &lt;element ref="{}Private_ind" minOccurs="0"/>
 *         &lt;element ref="{}Details" minOccurs="0"/>
 *         &lt;element ref="{}Created_by" minOccurs="0"/>
 *         &lt;element ref="{}Created_date" minOccurs="0"/>
 *         &lt;element ref="{}Updated_by" minOccurs="0"/>
 *         &lt;element ref="{}Updated_date" minOccurs="0"/>
 *         &lt;element ref="{}Record_version" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resElectronicAddressType", propOrder = {
    "id",
    "resInstanceId",
    "electronicAddressCode",
    "electronicAddressDescription",
    "messageDeviceCode",
    "messageDeviceDescription",
    "electronicAddress",
    "emailAddressableInd",
    "privateInd",
    "details",
    "createdBy",
    "createdDate",
    "updatedBy",
    "updatedDate",
    "recordVersion"
})

/**
 * An email. Added the interface implementation after auto-generation using JAXB. This was for compatibility in generic methods of the CsrToSrMappingServiceImpl.
 * @author james.somerville
 *
 */
public class ResElectronicAddressType implements CsrElement {

    @XmlElement(name = "Id")
    protected BigInteger id;
    @XmlElement(name = "Res_instance_id")
    protected BigInteger resInstanceId;
    @XmlElement(name = "Electronic_address_code")
    protected String electronicAddressCode;
    @XmlElement(name = "Electronic_address_description")
    protected String electronicAddressDescription;
    @XmlElement(name = "Message_device_code")
    protected String messageDeviceCode;
    @XmlElement(name = "Message_device_description")
    protected String messageDeviceDescription;
    @XmlElement(name = "Electronic_address")
    protected String electronicAddress;
    @XmlElement(name = "Email_addressable_ind")
    protected String emailAddressableInd;
    @XmlElement(name = "Private_ind")
    protected String privateInd;
    @XmlElement(name = "Details")
    protected String details;
    @XmlElement(name = "Created_by")
    protected BigInteger createdBy;
    @XmlElement(name = "Created_date")
    protected String createdDate;
    @XmlElement(name = "Updated_by")
    protected BigInteger updatedBy;
    @XmlElement(name = "Updated_date")
    protected String updatedDate;
    @XmlElement(name = "Record_version")
    protected BigInteger recordVersion;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the resInstanceId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getResInstanceId() {
        return resInstanceId;
    }

    /**
     * Sets the value of the resInstanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setResInstanceId(BigInteger value) {
        this.resInstanceId = value;
    }

    /**
     * Gets the value of the electronicAddressCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElectronicAddressCode() {
        return electronicAddressCode;
    }

    /**
     * Sets the value of the electronicAddressCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElectronicAddressCode(String value) {
        this.electronicAddressCode = value;
    }

    /**
     * Gets the value of the electronicAddressDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElectronicAddressDescription() {
        return electronicAddressDescription;
    }

    /**
     * Sets the value of the electronicAddressDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElectronicAddressDescription(String value) {
        this.electronicAddressDescription = value;
    }

    /**
     * Gets the value of the messageDeviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageDeviceCode() {
        return messageDeviceCode;
    }

    /**
     * Sets the value of the messageDeviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageDeviceCode(String value) {
        this.messageDeviceCode = value;
    }

    /**
     * Gets the value of the messageDeviceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageDeviceDescription() {
        return messageDeviceDescription;
    }

    /**
     * Sets the value of the messageDeviceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageDeviceDescription(String value) {
        this.messageDeviceDescription = value;
    }

    /**
     * Gets the value of the electronicAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElectronicAddress() {
        return electronicAddress;
    }

    /**
     * Sets the value of the electronicAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElectronicAddress(String value) {
        this.electronicAddress = value;
    }

    /**
     * Gets the value of the emailAddressableInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddressableInd() {
        return emailAddressableInd;
    }

    /**
     * Sets the value of the emailAddressableInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddressableInd(String value) {
        this.emailAddressableInd = value;
    }

    /**
     * Gets the value of the privateInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateInd() {
        return privateInd;
    }

    /**
     * Sets the value of the privateInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateInd(String value) {
        this.privateInd = value;
    }

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetails(String value) {
        this.details = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCreatedBy(BigInteger value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDate(String value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUpdatedBy(BigInteger value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the updatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @SuppressWarnings("unchecked")
    public String getUpdatedDate() {
        return updatedDate;
    }

    /**
     * Sets the value of the updatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedDate(String value) {
        this.updatedDate = value;
    }

    /**
     * Gets the value of the recordVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecordVersion() {
        return recordVersion;
    }

    /**
     * Sets the value of the recordVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecordVersion(BigInteger value) {
        this.recordVersion = value;
    }

}
