//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 04:00:13 PM EST 
//


package city.baltimore.eip.model.motorola.csr;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import city.baltimore.eip.model.CsrElement;


/**
 * <p>Java class for resNameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resNameType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Id" minOccurs="0"/>
 *         &lt;element ref="{}Res_instance_id" minOccurs="0"/>
 *         &lt;element ref="{}Owner_group_code" minOccurs="0"/>
 *         &lt;element ref="{}Owner_group_description" minOccurs="0"/>
 *         &lt;element ref="{}Name_type_item_code" minOccurs="0"/>
 *         &lt;element ref="{}Name_type_item_description" minOccurs="0"/>
 *         &lt;element ref="{}Display_name" minOccurs="0"/>
 *         &lt;element ref="{}Search_display_name" minOccurs="0"/>
 *         &lt;element ref="{}Name_field_01" minOccurs="0"/>
 *         &lt;element ref="{}Name_field_02" minOccurs="0"/>
 *         &lt;element ref="{}Name_field_03" minOccurs="0"/>
 *         &lt;element ref="{}Name_field_04" minOccurs="0"/>
 *         &lt;element ref="{}Name_field_05" minOccurs="0"/>
 *         &lt;element ref="{}Name_field_06" minOccurs="0"/>
 *         &lt;element ref="{}Created_by" minOccurs="0"/>
 *         &lt;element ref="{}Created_date" minOccurs="0"/>
 *         &lt;element ref="{}Updated_by" minOccurs="0"/>
 *         &lt;element ref="{}Updated_date" minOccurs="0"/>
 *         &lt;element ref="{}Record_version" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resNameType", propOrder = {
    "id",
    "resInstanceId",
    "ownerGroupCode",
    "ownerGroupDescription",
    "nameTypeItemCode",
    "nameTypeItemDescription",
    "displayName",
    "searchDisplayName",
    "nameField01",
    "nameField02",
    "nameField03",
    "nameField04",
    "nameField05",
    "nameField06",
    "createdBy",
    "createdDate",
    "updatedBy",
    "updatedDate",
    "recordVersion"
})

/**
 * A person's name. Added the interface implementation after auto-generation using JAXB. This was for compatibility in generic methods of the CsrToSrMappingServiceImpl.
 * @author james.somerville
 *
 */
public class ResNameType implements CsrElement {

    @XmlElement(name = "Id")
    protected BigInteger id;
    @XmlElement(name = "Res_instance_id")
    protected BigInteger resInstanceId;
    @XmlElement(name = "Owner_group_code")
    protected String ownerGroupCode;
    @XmlElement(name = "Owner_group_description")
    protected String ownerGroupDescription;
    @XmlElement(name = "Name_type_item_code")
    protected String nameTypeItemCode;
    @XmlElement(name = "Name_type_item_description")
    protected String nameTypeItemDescription;
    @XmlElement(name = "Display_name")
    protected String displayName;
    @XmlElement(name = "Search_display_name")
    protected String searchDisplayName;
    @XmlElement(name = "Name_field_01")
    protected String nameField01;
    @XmlElement(name = "Name_field_02")
    protected String nameField02;
    @XmlElement(name = "Name_field_03")
    protected String nameField03;
    @XmlElement(name = "Name_field_04")
    protected String nameField04;
    @XmlElement(name = "Name_field_05")
    protected String nameField05;
    @XmlElement(name = "Name_field_06")
    protected String nameField06;
    @XmlElement(name = "Created_by")
    protected BigInteger createdBy;
    @XmlElement(name = "Created_date")
    protected String createdDate;
    @XmlElement(name = "Updated_by")
    protected BigInteger updatedBy;
    @XmlElement(name = "Updated_date")
    protected String updatedDate;
    @XmlElement(name = "Record_version")
    protected BigInteger recordVersion;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the resInstanceId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getResInstanceId() {
        return resInstanceId;
    }

    /**
     * Sets the value of the resInstanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setResInstanceId(BigInteger value) {
        this.resInstanceId = value;
    }

    /**
     * Gets the value of the ownerGroupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerGroupCode() {
        return ownerGroupCode;
    }

    /**
     * Sets the value of the ownerGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerGroupCode(String value) {
        this.ownerGroupCode = value;
    }

    /**
     * Gets the value of the ownerGroupDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerGroupDescription() {
        return ownerGroupDescription;
    }

    /**
     * Sets the value of the ownerGroupDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerGroupDescription(String value) {
        this.ownerGroupDescription = value;
    }

    /**
     * Gets the value of the nameTypeItemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameTypeItemCode() {
        return nameTypeItemCode;
    }

    /**
     * Sets the value of the nameTypeItemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameTypeItemCode(String value) {
        this.nameTypeItemCode = value;
    }

    /**
     * Gets the value of the nameTypeItemDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameTypeItemDescription() {
        return nameTypeItemDescription;
    }

    /**
     * Sets the value of the nameTypeItemDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameTypeItemDescription(String value) {
        this.nameTypeItemDescription = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the searchDisplayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchDisplayName() {
        return searchDisplayName;
    }

    /**
     * Sets the value of the searchDisplayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchDisplayName(String value) {
        this.searchDisplayName = value;
    }

    /**
     * Gets the value of the nameField01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameField01() {
        return nameField01;
    }

    /**
     * Sets the value of the nameField01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameField01(String value) {
        this.nameField01 = value;
    }

    /**
     * Gets the value of the nameField02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameField02() {
        return nameField02;
    }

    /**
     * Sets the value of the nameField02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameField02(String value) {
        this.nameField02 = value;
    }

    /**
     * Gets the value of the nameField03 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameField03() {
        return nameField03;
    }

    /**
     * Sets the value of the nameField03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameField03(String value) {
        this.nameField03 = value;
    }

    /**
     * Gets the value of the nameField04 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameField04() {
        return nameField04;
    }

    /**
     * Sets the value of the nameField04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameField04(String value) {
        this.nameField04 = value;
    }

    /**
     * Gets the value of the nameField05 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameField05() {
        return nameField05;
    }

    /**
     * Sets the value of the nameField05 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameField05(String value) {
        this.nameField05 = value;
    }

    /**
     * Gets the value of the nameField06 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameField06() {
        return nameField06;
    }

    /**
     * Sets the value of the nameField06 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameField06(String value) {
        this.nameField06 = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCreatedBy(BigInteger value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDate(String value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUpdatedBy(BigInteger value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the updatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @SuppressWarnings("unchecked")
    public String getUpdatedDate() {
        return updatedDate;
    }

    /**
     * Sets the value of the updatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedDate(String value) {
        this.updatedDate = value;
    }

    /**
     * Gets the value of the recordVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecordVersion() {
        return recordVersion;
    }

    /**
     * Sets the value of the recordVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecordVersion(BigInteger value) {
        this.recordVersion = value;
    }

}
